apiVersion: v1
kind: Namespace
metadata: {name: istio-system}
---
apiVersion: v1
kind: Namespace
metadata: {name: forwardmeasure-platform}
---
apiVersion: v1
kind: Namespace
metadata: {name: cert-manager}
---
apiVersion: v1
kind: Namespace
metadata: {name: external-secrets}
---
apiVersion: v1
kind: Namespace
metadata: {name: keycloak}
---
apiVersion: v1
kind: Namespace
metadata: {name: strimzi-operator}
---
apiVersion: v1
kind: Namespace
metadata: {name: kafka}
---
apiVersion: v1
kind: Namespace
metadata: {name: apicurio-registry}
---
apiVersion: v1
kind: Namespace
metadata: {name: opensearch-cluster}
---
apiVersion: v1
kind: Namespace
metadata: {name: kserve}
---
apiVersion: v1
kind: Namespace
metadata: {name: knative-operator}
---
apiVersion: v1
kind: Namespace
metadata: {name: knative-serving}
---
apiVersion: v1
kind: Namespace
metadata: {name: knative-eventing}
---
apiVersion: v1
kind: Namespace
metadata: {name: kserve-serving}
---
apiVersion: v1
kind: Namespace
metadata: {name: docling-serve}
---
apiVersion: v1
kind: Namespace
metadata: {name: valkey}
---
apiVersion: v1
kind: Namespace
metadata: {name: superset}
