chartVersions:
  istio: "1.30.2"
  certManager: "v1.21.0"
  externalSecrets: "2.0.1"
  platformSecrets: "0.1.5"
  platformRouting: "0.0.11"
  keycloak: "0.0.22"
  strimzi: "1.1.0"
  kafka: "0.0.4"
  apicurioOperator: "0.1.2"
  apicurioDeployment: "0.1.2"
  openSearch: "0.1.4"
  kserve: "v0.17.0"
  knativeOperator: "1.22.3"
  knativeResources: "0.0.18"
  modelCache: "0.1.8"
  modelServing: "0.1.26"
  docling: "0.0.7"
  valkey: "0.9.3"
  superset: "0.15.2"
